### ISSUE TITLE
iPhone Authentication Broken

### ISSUE THREAD

**Issue by hasis** [fitrpg/fitrpg-server#79]
Hey friends!

Is this still in active development? I'm having trouble authenticating the app, and it sounds like what a lot of these folks are seeing as well:

https://searchman.com/ios/app/us/887067605/en/fatchicken-studios/fitrpg-gamifying-fitbit/

Getting a 401 when authenticating.

Thanks!

**Comment by nurseybushc** [comment]
There is no work currently being done on this repo. I have forked it and am slowly fixing issues and adding more features. The server fork is https://github.com/nurseymybush/fitrpg-server and the ionic app fork is https://github.com/nurseymybush/fitrpg-ionic. After am satisfied with my additions, I will do a pull-request for both.
